dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
branches:
  only:
    - core
before_script:
  - chmod a+x ./travis-build.sh
script:
  - ./travis-build.sh
notifications:
  email:
    on_success: never
    on_failure: always