dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
branches:
  only:
    - core
before_script:
  - chmod a+x ./GenieCLI/travis-build.sh
script:
  - ./GenieCLI/travis-build.sh
notifications:
  email:
    on_success: never
    on_failure: always