image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test Genie.Tests" -filter:"+[*]* -[xunit*]*" -output:".\Coverage.xml" -oldstyle
- codecov -f ".\Coverage.xml" -t 2a219bc0-2479-4e8b-8414-c81e89eee6aa